### PR TITLE
Send gRPC errors properly

### LINKED ISSUE #1933: Handle errors with gRPC
It is throwing HTTP status codes like 429 or 503 when a gRPC action throws. It instead needs to return HTTP 200 always and instead set the grpc-status header. This should let me have more detailed error messaging, instead of a generic IOException

### PR DESCRIPTION
**Pull request by ewolak-sq**
According to the [gRPC spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md), all
gRPC responses, including errors, should have an HTTP status of 200. gRPC errors are signaled using
the `grpc-status` header. This brings Misk in compliance with the spec, translating HTTP errors into
properly formatted gRPC errors.

Fixes #1933

### CODE REVIEW

File: misk/src/main/kotlin/misk/web/HttpCall.kt [hunk 1]
```diff
@@ -31,7 +31,12 @@ interface HttpCall {
   val requestHeaders: Headers
 
   /** The HTTP response under construction. */
+  /** Meaningful HTTP status about what actually happened */
```
Comment (r3mariano) [inline misk/src/main/kotlin/misk/web/HttpCall.kt:34]: nit: remove old javadoc comment, and add comment about how this may not be the code actually sent over the network and why this is the case. I see it's commented elsewhere, but adding the comment here too will help reduce confusion

File: misk-grpc-tests/src/test/kotlin/misk/grpc/MiskClientMiskServerTest.kt [hunk 2]
```diff
@@ -105,4 +110,55 @@ class MiskClientMiskServerTest {
...
+
+    runBlocking {
+      val e = assertFailsWith<GrpcException> {
+        routeGuide.GetFeature().execute(point)
+      }
+      assertThat(e.grpcMessage).isEqualTo("unexpected latitude error!")
+      assertThat(e.grpcStatus).isEqualTo(GrpcStatus.UNKNOWN)
+
+      assertResponseCount(200, 0)
+      assertResponseCount(500, 1)
```
Comment (r3mariano) [inline misk-grpc-tests/src/test/kotlin/misk/grpc/MiskClientMiskServerTest.kt:129]: This test is broken; will approve when it passes.

Also, nit: add code comment about why these are the expected metrics

File: misk/src/main/kotlin/misk/web/exceptions/ExceptionHandlingInterceptor.kt [hunk 3]
```diff
@@ -37,13 +45,67 @@ class ExceptionHandlingInterceptor(
...
+    }
+  }
+
+  /**
+   * Borrow behavior from [GrpcFeatureBinding] to send a gRPC error with an HTTP 200 status code.
+   * This is weird but it's how gRPC clients work.
+   *
+   * One thing to note is for our metrics we want to pretend that the HTTP code is what we sent.
+   * Otherwise gRPC requests that crashed and yielded an HTTP 200 code will confuse operators.
+   */
```
Comment (r3mariano) [inline misk/src/main/kotlin/misk/web/exceptions/ExceptionHandlingInterceptor.kt:69]: I see that this will reduce disruption with metrics, but I feel like having two sets of HTTP status codes is confusing in the long run, and it adds a layer of indirection with gRPC statuses. Why not have a metric for different gRPC statuses instead?

To provide a good migration path, we can probably emit both HTTP and gRPC status code metrics, then turn off HTTP status code metrics for gRPC endpoints later.

File: misk-grpc-tests/src/main/kotlin/misk/grpc/miskserver/GetFeatureGrpcAction.kt [hunk 4]
```diff
@@ -10,6 +11,9 @@ import javax.inject.Inject
 class GetFeatureGrpcAction @Inject constructor() : WebAction, RouteGuideGetFeatureBlockingServer {
   @LogRequestResponse(bodySampling = 1.0, errorBodySampling = 1.0)
   override fun GetFeature(request: Point): Feature {
+    if (request.latitude == -1) {
+      throw WebActionException(request.longitude ?: 500, "unexpected latitude error!")
+    }
```
Comment (r3mariano) [inline misk-grpc-tests/src/main/kotlin/misk/grpc/miskserver/GetFeatureGrpcAction.kt:16]: This feels so hacky lol. How about a separate RPC that always fails?

File: misk/src/main/kotlin/misk/web/exceptions/ExceptionHandlingInterceptor.kt (hunk 3 above)
Comment (r3mariano) [reply misk/src/main/kotlin/misk/web/exceptions/ExceptionHandlingInterceptor.kt:69]: Suggest new metrics that look like these, but no real need to make them identical I think? https://github.com/grpc-ecosystem/java-grpc-prometheus

Comment (r3mariano) [reply misk/src/main/kotlin/misk/web/exceptions/ExceptionHandlingInterceptor.kt:69]: (fwiw, this is fine to keep as is in this PR)

File: misk/src/main/kotlin/misk/web/HttpCall.kt [hunk 5]
```diff
@@ -31,7 +31,12 @@ interface HttpCall {
...
   var statusCode: Int
+
+  /** The HTTP status code actually sent over the network. For gRPC, this is *always* 200, even
+   * for errors. */
+  var networkStatusCode: Int
```
Comment (swankjesse) [inline misk/src/main/kotlin/misk/web/HttpCall.kt:39]: # 👍🏻

File: misk/src/main/kotlin/misk/web/ServletHttpCall.kt [hunk 6]
```diff
@@ -25,8 +25,16 @@ internal data class ServletHttpCall(
...
+    get() = _actualStatusCode ?: upstreamResponse.statusCode
+    set(value) {
+      _actualStatusCode = value
+      upstreamResponse.statusCode = value
+    }
+
+  override var networkStatusCode: Int
     get() = upstreamResponse.statusCode
     set(value) {
       upstreamResponse.statusCode = value
```
Comment (swankjesse) [inline misk/src/main/kotlin/misk/web/ServletHttpCall.kt:40]: there’s a bit of a hazard here where you gotta set this one last. Ugh!

Maybe add a function and make `networkStatusCode` a val?

```
fun setStatusCodes(statusCode: Int, networkStatusCode: Int) { ... }
```

File: misk/src/main/kotlin/misk/web/exceptions/ExceptionHandlingInterceptor.kt (hunk 3 above)
Comment (swankjesse) [reply misk/src/main/kotlin/misk/web/exceptions/ExceptionHandlingInterceptor.kt:69]: gRPC is always 200 OK, even when it’s not okay, and that is awful and a guarantee that there will be confusion. 

My preference is that we try to hide the insincere 200 OKs in implementation details. Metrics and alerting and even just developer expectations are pretty invested in 200/400/500 meaning different things. The 200 is a lie, and we want to quietly send it over the Wire without spreading that lie to other systems.

I think trying to get all those downstream tools to have independent HTTP and gRPC modes only spreads the confusion.

**Review by swankjesse — APPROVED** [review]

File: misk/src/main/kotlin/misk/web/exceptions/ExceptionHandlingInterceptor.kt (hunk 3 above)
Comment (r3mariano) [reply misk/src/main/kotlin/misk/web/exceptions/ExceptionHandlingInterceptor.kt:69]: I get that gRPC errors being HTTP 200 is confusing. Thinking about it more, my concerns are a) [HTTP 4xx/5xx and gRPC have a non-1:1 mapping with different semantics](https://grpc.github.io/grpc/core/md_doc_http-grpc-status-mapping.html), and b) hiding the HTTP and gRPC status makes it a bit more difficult to trace requests when debugging (e.g. the server said 502 in its logs, but the client got a 200).

I see what you mean with metrics though, and am ok with having a mapping for metrics purposes.

File: misk-grpc-tests/src/test/kotlin/misk/grpc/MiskClientMiskServerTest.kt (hunk 2 above)
Comment (ewolak-sq) [reply misk-grpc-tests/src/test/kotlin/misk/grpc/MiskClientMiskServerTest.kt:129]: Can you be more specific about what you mean by "broken" here? The assertion is about what's counted in metrics, which we very much do want to be what's asserted here. See the discussion in https://github.com/cashapp/misk/pull/1983#discussion_r655746280

File: misk-grpc-tests/src/main/kotlin/misk/grpc/miskserver/GetFeatureGrpcAction.kt (hunk 4 above)
Comment (ewolak-sq) [reply misk-grpc-tests/src/main/kotlin/misk/grpc/miskserver/GetFeatureGrpcAction.kt:16]: I'm pretty sure that the `RouteGuide` service is borrowed from the gRPC reference implementation, so I'm loathe to extend that with another method just for this sort of test. Given that it's strictly test code, I'm not sure I agree that it's worth doing in a perfect way.

@swankjesse what do you think?

File: misk/src/main/kotlin/misk/web/ServletHttpCall.kt (hunk 6 above)
Comment (ewolak-sq) [reply misk/src/main/kotlin/misk/web/ServletHttpCall.kt:40]: Yeah, good call

**Comment by ewolak-sq** [comment]
I'm fairly certain that the test failure on `GrpcConnectivityTest` is a flake. I have it passing and failing locally with the same sets of tests before it, so it's definitely flaking. See #1853.

File: misk-grpc-tests/src/test/kotlin/misk/grpc/MiskClientMiskServerTest.kt (hunk 2 above)
Comment (r3mariano) [reply misk-grpc-tests/src/test/kotlin/misk/grpc/MiskClientMiskServerTest.kt:132]: Ah I saw a test failure here, but it looks like it's working now.

**Review by r3mariano — APPROVED** [review]

File: misk/src/main/kotlin/misk/web/exceptions/ExceptionHandlingInterceptor.kt (hunk 3 above)
Comment (ewolak-sq) [reply misk/src/main/kotlin/misk/web/exceptions/ExceptionHandlingInterceptor.kt:69]: I agree we should emit some gRPC-specific metrics to improve observability, but I think we can do that as a follow-up PR (#1992). This PR strictly improves the situation from "Misk counts 4xx/5xx metrics but breaks gRPC clients" to "Misk counts 4xx/5xx metrics and doesn't break gRPC clients". The third option, of "Misk fails to count 4xx/5xx metrics for gRPC but clients get the right error responses" seems strictly worse than either of those to me.

**Comment by ewolak-sq** [comment]
@r3mariano @swankjesse 😠  I'm getting a _consistent_ failure with `okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL` in CI, but it won't fail locally. I think it's just #1853 rearing its head. What should I do to move forward?

**Comment by r3mariano** [comment]
> @r3mariano @swankjesse 😠 I'm getting a _consistent_ failure with `okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL` in CI, but it won't fail locally. I think it's just #1853 rearing its head. What should I do to move forward?

I've disabled the offending test in #2004.

**Comment by ewolak-sq** [comment]
Ugh. I think all these tests are flaky in different and interesting ways. `MiskClientMiskServerTest.serverFailureNotFound()` sometimes gets `java.io.IOException: gRPC transport failure (HTTP status=200, grpc-status=null, grpc-message=null)`, which I'm guessing is the same flakiness as in `GrpcConnectivityTest`. Then the metrics counts seem to have a race condition, so I probably need to await for them.

File: misk-grpc-tests/src/main/kotlin/misk/grpc/miskserver/GetFeatureGrpcAction.kt (hunk 4 above)
Comment (swankjesse) [reply misk-grpc-tests/src/main/kotlin/misk/grpc/miskserver/GetFeatureGrpcAction.kt:16]: Happy as is.
