### PR TITLE
Suggest endpoints in NotFoundAction response

### LINKED ISSUE #1162: Provide more context when the caller’s Content-Type is wrong
It’s super frustrating to call endpoints with the wrong Content-Type and get a 404. We should provide more context like so:

```
No such resource.

Received:
  POST /foo/bar
  Content-Type: none specified

Alternative:
  GET /foo/bar

Alternative:
  POST /foo/bar
  Content-Type: application/json
```

### PR DESCRIPTION
**Pull request by keeferrourke**
Closes #1162

### CODE REVIEW

File: misk/src/main/kotlin/misk/web/BoundAction.kt [hunk 1]
```diff
@@ -65,6 +65,17 @@ internal class BoundAction<A : WebAction>(
     )
   }
 
+  fun matchByUrl(url: HttpUrl): BoundActionMatch? {
+    val patchMather = pathPattern.matcher(url) ?: return null
+    return BoundActionMatch(
+        this,
```
Comment (adrw) [inline misk/src/main/kotlin/misk/web/BoundAction.kt]: Consider using Kotlin named paramters so it's more clear at call site.

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt [hunk 2]
```diff
@@ -1,29 +1,41 @@
...
   @Post("/{path:.*}")
   @RequestContentType(MediaTypes.ALL)
   @ResponseContentType(MediaTypes.ALL)
   @Unauthenticated
   fun notFound(@PathParam path: String): Response<ResponseBody> {
-    return response(path)
+    return Response(
+        body = notFoundMessage(path, clientHttpCall.get()).toResponseBody(),
+        headers = headersOf("Content-Type", MediaTypes.TEXT_PLAIN_UTF8),
+        statusCode = 404
```
Comment (adrw) [inline misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: Was NotFoundAction not returning a `404` before?

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt [hunk 3]
```diff
@@ -38,4 +50,40 @@ class NotFoundAction @Inject constructor() : WebAction {
       )
     }
   }
+
+  /** Generates a message for a client that hints what may have been wrong with their request. */
+  private fun notFoundMessage(path: String, httpCall: HttpCall) = buildString {
```
Comment (adrw) [inline misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: Nice use of `buildString`

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt [hunk 4]
```diff
@@ -38,4 +50,40 @@ class NotFoundAction @Inject constructor() : WebAction {
...
+    val boundActions = servletProvider.get().boundActions
+    val alternativeActions = boundActions.mapNotNull {
+      it.matchByUrl(httpCall.url)
+    }.filterNot { it.action.pathPattern.matchesWildcardPath }
+
+    append("Nothing found at /$path.\n\n")
+    append("Received:\n")
+    append("  ${httpCall.dispatchMechanism.method} /$path\n")
+    for (accept in httpCall.accepts()) {
+      append("  Accept: $accept\n")
```
Comment (acostama) [inline misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: nit: have the `Accept` line follow the `Content-Type` as in the alternative (or the other way around)

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt [hunk 5]
```diff
@@ -38,4 +50,40 @@ class NotFoundAction @Inject constructor() : WebAction {
...
+  /** Generates a message for a client that hints what may have been wrong with their request. */
+  private fun notFoundMessage(path: String, httpCall: HttpCall) = buildString {
+    val boundActions = servletProvider.get().boundActions
+    val alternativeActions = boundActions.mapNotNull {
+      it.matchByUrl(httpCall.url)
+    }.filterNot { it.action.pathPattern.matchesWildcardPath }
+
+    append("Nothing found at /$path.\n\n")
+    append("Received:\n")
+    append("  ${httpCall.dispatchMechanism.method} /$path\n")
```
Comment (adrw) [inline misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: Consider an explicit indentation character like `\t` or the following which only need to be set once vs. manually adding spaces.

- Increase indent: `⇥`
- Decrease indent: `⇤`

File: misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt [hunk 6]
```diff
@@ -85,6 +89,61 @@ class NotFoundActionTest {
...
+      |  Accept: */*
+      |  Content-Type: application/weird; charset=utf-8
+      |
+      |Alternative:
+      |  POST /echo
+      |  Content-Type: text/plain;charset=utf-8
+      |  Accept: text/plain;charset=utf-8
+      |""".trimMargin())
+  }
+  @Test fun responseMessageSuggestsAcceptType() {
```
Comment (adrw) [inline misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt]: nit: add new line above.

File: misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt [hunk 7]
```diff
@@ -85,6 +89,61 @@ class NotFoundActionTest {
     assertThat(response.code).isEqualTo(404)
   }
 
+  @Test fun responseMessageSuggestsAlternativeMethod() {
+    val wrongMethod = get("/echo", plainTextMediaType)
+    val response = httpClient.newCall(wrongMethod).execute()
+    assertThat(response.code).isEqualTo(404)
+    assertThat(response.body!!.source().readUtf8()).isEqualTo("""
```
Comment (adrw) [inline misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt]: Nice tests

File: misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt [hunk 8]
```diff
@@ -110,14 +169,35 @@ class NotFoundActionTest {
     return Request.Builder()
         .post(content.toRequestBody(contentType))
         .url(jettyService.httpServerUrl.newBuilder().encodedPath(path).build())
-        .header("Accept", acceptedMediaType.toString())
+        .apply {
+          if (acceptedMediaType != null)
```
Comment (adrw) [inline misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt]: Add braces for if statement

File: misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt [hunk 9]
```diff
@@ -110,14 +169,35 @@ class NotFoundActionTest {
...
+            header("Accept", acceptedMediaType.toString())
```
Comment (adrw) [inline misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt]: Does the request blow up if Accept header isn't passed in?

File: misk/src/test/kotlin/misk/web/proxy/WebProxyActionTest.kt [hunk 10]
```diff
@@ -161,7 +160,13 @@ class WebProxyActionTest {
   internal fun getNotForwardedPathNoMatch() {
     val request = get("/local/notredirectedprefix/tacos", weirdMediaType)
     val response = optionalBinder.proxyClient.newCall(request).execute().toMisk()
-    assertThat(response.readUtf8()).isEqualTo("Nothing found at /local/notredirectedprefix/tacos")
+    assertThat(response.readUtf8()).isEqualTo("""
```
Comment (adrw) [inline misk/src/test/kotlin/misk/web/proxy/WebProxyActionTest.kt]: Thanks for updating these tests

File: misk/src/test/kotlin/misk/web/proxy/WebProxyActionTest.kt [hunk 11]
```diff
@@ -224,7 +229,16 @@ class WebProxyActionTest {
...
+      |No such resource.
+      |
+      |Received:
+      |  POST /local/notredirectedprefix/tacos
+      |  Accept: application/weird
+      |  Content-Type: application/weird; charset=utf-8
+      |""".trimMargin())
+
+        // "Nothing found at /local/notredirectedprefix/tacos")
```
Comment (adrw) [inline misk/src/test/kotlin/misk/web/proxy/WebProxyActionTest.kt]: rm comment

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt (hunk 2 above)
Comment (swankjesse) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: nah, it was on the old line 37

File: misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt (hunk 9 above)
Comment (keeferrourke) [reply misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt]: Heh, yeah it sends the string "null" as the accept header value, which throws
```
java.lang.IllegalArgumentException: null is not a valid media range
	at misk.web.mediatype.MediaRange$Companion.parse(MediaRange.kt:87)
	at misk.web.mediatype.MediaRange$Companion.parseRanges(MediaRange.kt:81)
	at misk.web.HttpCall$DefaultImpls.accepts(HttpCall.kt:101)
	at misk.web.ServletHttpCall.accepts(ServletHttpCall.kt:13)
	at misk.web.jetty.WebActionsServlet.handleCall(WebActionsServlet.kt:65)
	at misk.web.jetty.WebActionsServlet.doPost(WebActionsServlet.kt:51)
...
```

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt [hunk 12]
```diff
@@ -38,4 +50,40 @@ class NotFoundAction @Inject constructor() : WebAction {
       )
     }
   }
+
+  /** Generates a message for a client that hints what may have been wrong with their request. */
+  private fun notFoundMessage(path: String, httpCall: HttpCall) = buildString {
+    val boundActions = servletProvider.get().boundActions
+    val alternativeActions = boundActions.mapNotNull {
+      it.matchByUrl(httpCall.url)
+    }.filterNot { it.action.pathPattern.matchesWildcardPath }
```
Comment (swankjesse) [inline misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: does this prevent it from matching useful things?

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt (hunk 5 above)
Comment (swankjesse) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: nooo tabs are bad!

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt (hunk 2 above)
Comment (keeferrourke) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: It was, but it was doing so with the `response()` method of its Companion, which isn't capable of providing the contextful response.

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt [hunk 13]
```diff
@@ -38,4 +50,40 @@ class NotFoundAction @Inject constructor() : WebAction {
...
+    for (i in 0 until alternativeActions.size) {
+      val alternative = alternativeActions[i]
+      val metadata = alternative.action.metadata
+      append("Alternative:\n")
+      append("  ${metadata.dispatchMechanism.method} ${metadata.pathPattern}\n")
+      for (requestContentType in metadata.requestMediaTypes) {
+        append("  Content-Type: $requestContentType\n")
+      }
+      append("  Accept: ${metadata.responseMediaType}\n")
+      if (i < alternativeActions.size - 1) {
```
Comment (swankjesse) [inline misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: you could make your life easier by moving this newline to the beginning of the loop and removing the check on line 71

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt (hunk 5 above)
Comment (adrw) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: Agreed 💯 . No indentation for the following lines would also be totally valid too!

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt (hunk 4 above)
Comment (keeferrourke) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: Fixed

File: misk/src/main/kotlin/misk/web/BoundAction.kt (hunk 1 above)
Comment (keeferrourke) [reply misk/src/main/kotlin/misk/web/BoundAction.kt]: Fixed

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt (hunk 5 above)
Comment (keeferrourke) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: Ah I just updated this to use tabs! What if I did `val INDENT = "  "` and used that everywhere? Would that be an okay solution?

File: misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt (hunk 6 above)
Comment (keeferrourke) [reply misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt]: Fixed

File: misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt (hunk 7 above)
Comment (keeferrourke) [reply misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt]: thanks!

File: misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt (hunk 8 above)
Comment (keeferrourke) [reply misk/src/test/kotlin/misk/web/actions/NotFoundActionTest.kt]: Fixed

File: misk/src/test/kotlin/misk/web/proxy/WebProxyActionTest.kt (hunk 11 above)
Comment (keeferrourke) [reply misk/src/test/kotlin/misk/web/proxy/WebProxyActionTest.kt]: Fixed, sorry about that!

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt (hunk 12 above)
Comment (keeferrourke) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: It might. 

I did this for two reasons:
1. Prevent from matching on `/{path: .*}` routes, which aren't useful suggestions.
2. Concerns about leaking too much information.

As @adrw mentioned:
> Curious about the security implications around giving more information on endpoints through the error messages. Otherwise looks good 👍

I don't want to suggest too much &mdash; just things that look like the caller is definitely aware of. If a client is making a call to weird wildcard path, they might not be provided any suggestions, but they _should_ know about what the endpoint they are trying to call requires... but they might not realize they forgot to set the right content-type, so context is still helpful.

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt (hunk 5 above)
Comment (adrw) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: I'd lean towards just not having an indent at all

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt (hunk 12 above)
Comment (adrw) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: Would there be a way to also only recommend paths that they have sufficient authentication to see?

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt (hunk 5 above)
Comment (keeferrourke) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: Removed the indentation. No tabs, no spaces, just info :)

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt (hunk 13 above)
Comment (keeferrourke) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: Fixed!

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt (hunk 12 above)
Comment (keeferrourke) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: I'd expect so. Exploring that as an option.

Comment (keeferrourke) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: The information leakage is very high. Not going to delve into this. Any info that would be leaked by this is already discoverable. 

Someone who really cares about this could deploy an interceptor or an endpoint that supercedes the behaviour of the NotFoundAction.

File: misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt [hunk 14]
```diff
@@ -38,4 +50,35 @@ class NotFoundAction @Inject constructor() : WebAction {
       )
     }
   }
-}
+
+  /** Generates a message for a client that hints what may have been wrong with their request. */
+  private fun notFoundMessage(path: String, httpCall: HttpCall) = buildString {
+    val boundActions = servletProvider.get().boundActions
```
Comment (jjestrel) [inline misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: Is it easy to get routes that match your own level of authentication

Comment (keeferrourke) [reply misk/src/main/kotlin/misk/web/actions/NotFoundAction.kt]: It's not :(
