### PR TITLE
Use a RepeatedTaskQueue in SqsJobConsumer

### LINKED ISSUE #1069: misk.jobqueue.sqs.QueueReceiver needs to handle errors in client call
[If the client call](https://github.com/cashapp/misk/blob/f7f2f432ec99ddf7c82a2e0b3685e4513c3c0335/misk-aws/src/main/kotlin/misk/jobqueue/sqs/SqsJobConsumer.kt#L67-L72) throws an exception it will kill the thread consuming the queue events.

### PR DESCRIPTION
**Pull request by ryanhall07**
This fixes #1069, which was originally a bug in RepeatedTaskQueue back
in the day. We should prefer using RepeatedTaskQueue instead of hand
rolling threads to prevent repeating the same mistakes. In addition, job
consumers will backoff if there is no work or run into errors.

Now every parallel job consumer runs as a RepeatedTask and each Task
consumes N messages and dispatches them to separate executor service for
running.

### CODE REVIEW

File: misk-aws/src/main/kotlin/misk/jobqueue/sqs/AwsSqsJobQueueConfig.kt [hunk 1]
```diff
@@ -22,6 +22,11 @@ class AwsSqsJobQueueConfig(
   /**
    * Number of jobs that can be processed concurrently.
    */
-  val consumer_thread_pool_size: Int = 4
+  val consumer_thread_pool_size: Int = 4,
+
+  /**
+   * The amount of jitter to use when scheduling backoff times.
+   */
+  val backoff_jitter_ms: Long = 50
```
Comment (mightyguava) [inline misk-aws/src/main/kotlin/misk/jobqueue/sqs/AwsSqsJobQueueConfig.kt]: is this just for testing?

File: misk-aws/src/main/kotlin/misk/jobqueue/sqs/SqsJobConsumer.kt [hunk 2]
```diff
@@ -53,70 +49,65 @@ internal class SqsJobConsumer @Inject internal constructor(
...
       }
-    }
 
-    override fun close() {
-      if (!subscriptions.remove(queueName, this)) return
-
-      log.info { "closing subscription to queue ${queueName.value}" }
-      running.set(false)
+      return when {
+        failure.get() -> Status.FAILED
```
Comment (mightyguava) [inline misk-aws/src/main/kotlin/misk/jobqueue/sqs/SqsJobConsumer.kt]: don't you need to wait for the dispatched tasks to complete before checking this?

File: misk/src/main/kotlin/misk/tasks/RepeatedTaskQueueConfig.kt [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+import misk.backoff.ExponentialBackoff
+import java.time.Duration
+
+data class RepeatedTaskQueueConfig(
+  /**
+   * The default amount of jitter to use when scheduling backoffs.
+   *
+   * Can be overridden when scheduling a tasks.
+   */
+  val default_jitter_ms: Long = 50,
```
Comment (mightyguava) [inline misk/src/main/kotlin/misk/tasks/RepeatedTaskQueueConfig.kt]: is this just for tests?

Comment (ryanhall07) [reply misk/src/main/kotlin/misk/tasks/RepeatedTaskQueueConfig.kt]: well i'm using it for tests, but it seems reasonable to make it configurable

File: misk-aws/src/main/kotlin/misk/jobqueue/sqs/SqsJobConsumer.kt (hunk 2 above)
Comment (ryanhall07) [reply misk-aws/src/main/kotlin/misk/jobqueue/sqs/SqsJobConsumer.kt]: umm yea. should probably have a test :(

Comment (ryanhall07) [reply misk-aws/src/main/kotlin/misk/jobqueue/sqs/SqsJobConsumer.kt]: fixed in 9cdece6a298d316f06d8cbd6a2d8920ce4526c44

File: misk-aws/src/main/kotlin/misk/jobqueue/sqs/SqsJobConsumer.kt [hunk 4]
```diff
@@ -94,20 +96,24 @@ internal class SqsJobConsumer @Inject internal constructor(
...
       }
 
-      return when {
-        failure.get() -> Status.FAILED
-        messages.size == 0 -> Status.NO_WORK
-        else -> Status.OK
+      for (future in futures) {
+        try {
+          future.get()
+        } catch (e: Exception) {
```
Comment (mightyguava) [inline misk-aws/src/main/kotlin/misk/jobqueue/sqs/SqsJobConsumer.kt]: not `Throwable`?

Comment (ryanhall07) [reply misk-aws/src/main/kotlin/misk/jobqueue/sqs/SqsJobConsumer.kt]: it doesn't really matter here, you're not trying to prevent an Exception from being leaked (RepeatedTaskQueue handles that). Just trying to catch the signal that the dispatched handler threw an exception.

File: misk-aws/src/main/kotlin/misk/jobqueue/sqs/SqsJobConsumer.kt (hunk 2 above)
Comment (ryanhall07) [reply misk-aws/src/main/kotlin/misk/jobqueue/sqs/SqsJobConsumer.kt]: added a test too

File: misk-aws/src/main/kotlin/misk/jobqueue/sqs/ForSqsConsumer.kt [hunk 5]
```diff
@@ -3,4 +3,5 @@ package misk.jobqueue.sqs
 import javax.inject.Qualifier
 
 @Qualifier
-internal annotation class ForSqsConsumer
\ No newline at end of file
+@Target(AnnotationTarget.FIELD, AnnotationTarget.FUNCTION, AnnotationTarget.VALUE_PARAMETER)
```
Comment (mmihic) [inline misk-aws/src/main/kotlin/misk/jobqueue/sqs/ForSqsConsumer.kt]: hm, what necessitated this change (it's fine by me, just curious)

File: misk-aws/src/main/kotlin/misk/jobqueue/sqs/SqsJobConsumer.kt [hunk 6]
```diff
@@ -53,70 +49,76 @@ internal class SqsJobConsumer @Inject internal constructor(
...
+
+      val futures = messages.map { SqsJob(queueName, queues, metrics, it) }.map { message ->
+        dispatchThreadPool.submit {
+          metrics.jobsReceived.labels(queueName.value).inc()
+
+          tracer.traceWithSpan("handle-job-${queueName.value}") { span ->
+            // If the incoming job has an original trace id, set that as a tag on the new span.
+            // We don't turn that into the parent of the current span because that would
+            // incorrectly include the execution time of the job in the execution time of the
+            // action that triggered the job        q
```
Comment (mmihic) [inline misk-aws/src/main/kotlin/misk/jobqueue/sqs/SqsJobConsumer.kt]: trailing `    q`

File: misk-aws/src/main/kotlin/misk/jobqueue/sqs/ForSqsConsumer.kt (hunk 5 above)
Comment (ryanhall07) [reply misk-aws/src/main/kotlin/misk/jobqueue/sqs/ForSqsConsumer.kt]: so you could field inject in the test

```@Inject @ForSqsConsumer RepeatedTaskQueue```

Comment (ryanhall07) [reply misk-aws/src/main/kotlin/misk/jobqueue/sqs/ForSqsConsumer.kt]: without having to do `@field:ForSqsConsumer`
